[project]
name = "jp-datasets"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastexcel>=0.12.1",
    "polars>=1.22.0",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pynvim>=0.5.2",
]
